[build]
  command = "npm run build"
  publish = "."

# WWW -> apex (idolbrands.com)
[[redirects]]
  from = "/*"
  to = "https://idolbrands.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["www.idolbrands.com"] }

[[headers]]
  for = "/llms.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/*.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"
    Cache-Control = "public, max-age=600"
    X-Robots-Tag = "noindex"
